name: Rog Art Photography
favicon: null
layout_spectrum: 1
typography_spectrum: 0.7418034174479544
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1b1b1b'
    - '#ddd9d6'
    - '#c74f49'
    - '#a8948a'
    - '#685e53'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.125
  rhythmicContrast: 0.75
purpose: []
